### ISSUE TITLE
Error when executing bundle.js

### ISSUE THREAD

**Issue by AFKoide** [spicy-wolf/spine-wallpaper-engine#14]
Hello.
When I try to execute bundle.js, an error window display.
![image](https://user-images.githubusercontent.com/60762504/219176619-b154d678-bfa9-4789-a1d4-4b24e78eaf81.png)

 I tried both 1.0.0 and 1.1.0, but each time, I get the same error message.

**Comment by spicy-wolf** [comment]
no, you shouldn't execute the bundle.js. the entry point of this project is **index.html**.

**Comment by spicy-wolf** [comment]
btw, to avoid cros issue on the local, please try => https://stackoverflow.com/questions/6084360/using-node-js-as-a-simple-web-server

**Comment by AFKoide** [comment]
I used your link to setup a html web server with node as well as python. None work.
It seems to load the files because I see them appear in both terminal when I load for the first time, but after, the screen stays blank and refreshing it doesn't change anything.
(Both CMD)
![image](https://user-images.githubusercontent.com/60762504/219496607-b2324ecb-568f-4bf5-8c48-b940ec0b78d3.png)

I also change the content of config.json to see if the error was from there. For exemple, making the file syntax wrong, giving the wrong file name, using differents images...
Each time, both cmd would display that an error happened in config.json (error code 402).

**Comment by spicy-wolf** [comment]
may i ask which version of your spine project? so far we only support 3.8

and another reason could be the ` config.json`. please make sure the z value is a negative value (e.g. -1000) because the camera is at (0, 0, 0)

**Comment by spicy-wolf** [comment]
and if possible, can you please also take a screenshot of your browser console logs/errors? then we can check if the spine files are loading properly

**Comment by AFKoide** [comment]
![image](https://user-images.githubusercontent.com/60762504/219506515-806e4b02-1638-4ad7-92d9-7260d6c3ccb0.png)
Seems like the website don't know the animation... That's weird since I found the animation's name using [this website](https://naganeko.pages.dev/chibi-gif/index38).
![image](https://user-images.githubusercontent.com/60762504/219506993-1b46dc29-96d6-49db-9df1-e9eb2696b211.png)

**Comment by spicy-wolf** [comment]
im thinking the skel file is not loaded properly. do you mind to share your spine project so i can debug the issue on my local?

**Comment by AFKoide** [comment]
Here they are
[assets.zip](https://github.com/spicy-wolf/spine-wallpaper-engine/files/10761690/assets.zip)

**Comment by spicy-wolf** [comment]
thanks!
and I think I got why they are not working. your project is on version **3.7.93**
![image](https://user-images.githubusercontent.com/89831155/219510394-959b13b5-187d-4576-8e33-e4e531df4291.png)

the Spine software has break changes to file formats on different versions
official ref, please check the versioning section => https://github.com/EsotericSoftware/spine-runtimes#versioning
and unfortunately, each runtime are not backward compatible

**Comment by spicy-wolf** [comment]
in this case, I recommend you to upgrade your spine animation to 3.8 (we are going to support 4.0 and 4.1 in the future as well)

**Comment by spicy-wolf** [comment]
official way to upgrade a project to a specific version:
http://en.esotericsoftware.com/spine-versioning#File-storage
http://en.esotericsoftware.com/spine-command-line-interface#Import)

**Comment by AFKoide** [comment]
Thanks
I will try... but the files aren't mine and I don't have spine. I guess I can try using with unity.

**Comment by spicy-wolf** [comment]
no problem 👍
